### ISSUE TITLE
How to handle unnamed PLA's?

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#10]
Currently, unnamed PLA's can't be locked because they are "red".  nzahn stated that he thought this was a potential problem due to the # of (legitimate) unnamed PLA's that will probably be created in the future.

Some ideas:

1) Use shared / merged whitelists.  This sounds good in theory, but I don't know if it works in practice.  People tend to keep to themselves and rarely, if ever, share whitelists.  However, if there were shared whitelists by region and/or state, and these were actively promoted and maintained by RC's and/or SM's, this would seem more feasible.

2) Don't flag/lock PLA's with missing names.  Probably not a good idea if we want to encourage naming PLA's that really need a name.

3) Allow manual locking of unnamed PLA's.  If user manually locks, it's assumed the name was intentionally left blank and flag can be removed.

4) Create a slightly different outline for unnamed PLA's vs named PLA's.  Users can see there's something different about them, but they don't show up bright red and visually pollute the map.

**Comment by t0cableguy** [comment]
Iin my experience unnamed parking lots should be something you white-list yourself. Its like whitelisting URL or phone numbers. You might not find one this time, but next time someone might find an appropriate name.

**Comment by mapomatic** [comment]
OK, that makes sense (and you have a lot more experience using WMEPH than I do).  I suppose we can just keep an eye on it and if it becomes a major nuisance and more people complain, we can re-open.  I'll mark this as" wontfix" and close it.

**Comment by mapomatic** [comment]
After discussing in more detail with t0, we're thinking it makes sense to flag unnamed PLA's blue, allow whitelisting them, and perhaps adding an option to ignore them so they show up green.

**Comment by kbuley** [comment]
I like this idea.

**Comment by t0cableguy** [comment]
Need to do operator PNH for these locations. The URL's and phones will probably be standard at least by the region.

**Comment by mapomatic** [comment]
Fixed in v1.1.54.  Will address t0's comment above in a new Issue.
