### ISSUE TITLE
Shopping and Services shouldn't trigger parent category warning

### ISSUE THREAD

**Issue by StormeHawke** [WazeUSA/WME-Place-Harmonizer#103]
Shopping and Services is a fairly common parent category to apply to a place, from UPS stores to storage companies

https://www.waze.com/editor/?env=usa&lon=-86.13853&lat=39.91429&zoom=6&mode=0&venues=179503503.1794772887.4002358

**Comment by helifino** [comment]
...especially if it's recommended from the regional PNH data.

**Comment by t0cableguy** [comment]
Fixed. Man I have some awesome April fools jokes lined up
