### ISSUE TITLE
New "Gas station" string does not scan

### ISSUE THREAD

**Issue by helifino** [WazeUSA/WME-Place-Harmonizer#106]
This string makes no sense to me: "Waze3rdParty gas stations should be kept instead of existing ones."

**Comment by t0cableguy** [comment]
This doesn't scan. Its a note for all gas stations. We are not to remove the Waze3rdParty edited or added gas stations. They are to be kept above all others, even above the old gas stations. That is against the old policy of keeping the old gas station place above all else.

**Comment by helifino** [comment]
The new note makes more sense, satisfying this issue.
