### ISSUE TITLE
Hospital/Medical category - Always give option of convert to Offices

### ISSUE THREAD

**Issue by StormeHawke** [WazeUSA/WME-Place-Harmonizer#11]
Currently for point Hospital/Medical the script attempts to guess if something looks like a hospital and offers to convert to Offices.  But in a great many cases it guesses wrong and only offers the option to change to area.

I'd like to suggest that for these point places the option of "Convert to Area" and "Convert to Offices" should be universally available, without trying to guess

**Comment by t0cableguy** [comment]
I have to agree with StormeHawke. the guessing is spotty. It either needs to be improved, or both options provided all the time for hospital/medical care.

**Comment by t0cableguy** [comment]
https://www.waze.com/editor/?env=usa&lon=-87.21078&lat=30.47643&zoom=6&mode=0&venues=178782513.1787759592.1034624

Definitely a hospital, but it flags "doesn't look like a hospital"

**Comment by helifino** [comment]
Some additional examples:

This one gives a 'check the wiki' warning, but no option to change to Office:
https://www.waze.com/editor/?env=usa&lon=-122.18175&lat=47.71428&zoom=7&venues=155845085.1558581923.1169406

This one is a Urgent Care (which is in the Alt Name), but gives the 'not a hospital' warning:
https://www.waze.com/editor/?env=usa&lon=-122.18335&lat=47.71397&zoom=7&venues=155845085.1558581923.1012840

Hope these help.

**Comment by t0cableguy** [comment]
1st one should definitely convert to office. Second one should probably be office. But might fall under med care in some regions

**Comment by StormeHawke** [comment]
This is why I filed this issue - I personally don't see that much value in the guessing.  We human beings can tell at a glance if something is a hospital or not (or maybe we need to look up the website to double check whether urgent care centers are 24x7), but coming up with rules to quantify that knowledge for a computer is the kind of thing google invests millions of dollars into machine learning for.  Given it's just a button click one way or another I don't think it's worth it.  I'd really be happy with two buttons - Convert to Offices and Convert to Area, maybe with a brief explanation

**Comment by t0cableguy** [comment]
Not sure showing the medical care option for every office is right though. Then it will show for every office type always.

**Comment by StormeHawke** [comment]
This would only trigger on point places marked as Hospital/Medical (as it does currently).  It wouldn't be on offices because presumably those have already been reviewed

**Comment by t0cableguy** [comment]
we have found the sheet that checks the rough matching for hospitals and schools. Any of these that aren't being caught should be reported via the "report script error" button. I'll do my best to make them provide the "change to offices" button.

**Comment by StormeHawke** [comment]
I disagree - there will always be some amount of guessing that will be wrong.  Even if you want to try to keep the guessing around, I'd like to be able to say "No, this isn't a hospital, please convert to offices".  It errs more often in the direction of incorrectly thinking something is a hospital than the other way around

**Comment by mapomatic** [comment]
This is kind of a hot-button issue, so bumping up in priority.  As of now, the consensus seems to be that we should remove the message completely once a place is locked to region standards.  The hospital check and spreadsheet should be changed to only flag "definitely not a hospital", not "might not be a hospital".  If the place is unlocked and meets the "definitely not a hospital" check, set severity = 3 (or 2?), and not whitelistable.  If it doesn't meet the check, then add an informational message only -- don't change the severity or lock-ability.  If unlocked, all will still get the special hospital highlight.  Please comment if I've gotten any of this wrong...

**Comment by t0cableguy** [comment]
https://docs.google.com/spreadsheets/d/1pDmenZA-3FOTvhlCq9yz1dnemTmS9l_njZQbu_jLVMI/edit?usp=drivesdk
 link to hospital list

**Comment by t0cableguy** [comment]
So the severity set up for this list is that it should be absolutely not a hospital. This is to force you to not save the place as is. There is a whitelist button but it should not have to be pressed to clear this error.

**Comment by jangliss** [comment]
With the introduction of the new doctor/clinic typing vs medical/hospital, does this need to be refactored/reviewed again?

**Comment by mapomatic** [comment]
I'm going to close this issue.  New issues can be added if needed.
