### ISSUE TITLE
Place Website button should always change to Store Locator if one is available.

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#121]
Noticed on a Starbucks that didn't have a localized name yet, so it had the "Place needs localization" flag.  Haven't checked yet if there are other scenarios where the button isn't changing properly.

**Comment by t0cableguy** [comment]
maybe we could fix this if we made a magical button appear that is green and says open url

**Comment by RavenDT** [comment]
I agree with @t0cableguy. I think there should be: "Place Website" and "Store Locator".
In the refactor, we can change the "Place Website" button to a picture of a globe so it'll be smaller.
Maybe we can even change the "Store Locator" button to a crosshair or bullseye icon.

**Comment by mapomatic** [comment]
The magical green button fixed this issue.
