### ISSUE TITLE
"Existing URL doesn't match PNH URL" highlight issue?

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#126]
Place is highlighted green on the map, but is blue in the panel:
https://www.waze.com/editor/?env=usa&lon=-84.41877&lat=38.02196&zoom=6&venues=180617596.1806044890.1290149

**Comment by t0cableguy** [comment]
this is kinda the same thing as the house number out of range flag. It may not be an issue at all. 
I (we/anybody) need to come up with regexmatches for  the places that have localized urls. wmeph can detect those with the proper setup.

**Comment by mapomatic** [comment]
The issue isn't that it's using a localized URL.  The place is green on the map but when you run WMEPH on it, the banner is showing blue.

**Comment by mapomatic** [comment]
I don't recall exactly what the issue was, but it's apparently been fixed.  Closing.
