### ISSUE TITLE
street name changing from selected name in wmeph dropdown choices

### ISSUE THREAD

**Issue by t0cableguy** [WazeUSA/WME-Place-Harmonizer#141]
Script version: 1.2.2
Permalink: https://www.waze.com/editor/?env=usa&lo ... 66.2078845
Place name: Essex Bank
Country: United States
--------
Describe the error: while attempting to put sandy Hook Rd as the street, it kept defaulting to a SR-396 for some reason.

If you remove the name from the street and apply, then re run wmeph, enter sandy hook rd into the street name dropdown, once you move off of the text box it changes to sr-396. verified several times in my tests.

**Comment by t0cableguy** [comment]
From: getOffYourDamnPhone 
To: t0cableguy 

Script version: 1.2.2
Permalink: https://www.waze.com/editor/?env=usa&lo ... m=8&mode=0
Place name: Claire's Accessories
Country: United States
--------
Describe the error: For this particular area, when I try to enter PGA Blvd, it shows up, I select it and then click Ok. Once I click Ok, the name is changed to Palm Tree Ln. It's quite annoying. :-/
getOffYourDamnPhone
 
Posts: 3
Joined: 2017-02-15, 10:42 am

**Comment by helifino** [comment]
I have noticed this bug in the past, usually clears for me by reloading WME.

**Comment by mapomatic** [comment]
I've disabled the street selection box in the banner and replaced with Edit Address button.  Not quite as convenient, but less error-prone.
