### ISSUE TITLE
Add button to "Offices" to ask if it should be a "Doctor/Clinic"

### ISSUE THREAD

**Issue by StormeHawke** [WazeUSA/WME-Place-Harmonizer#154]
I'm guesstimating that about 60% of places currently categorized as "Offices" should now be "Doctor/Clinic" now that the new category is available.  

Having just finished going through my entire LAM area and correcting places that were changed to "Doctor/Clinic" back to "Hospital" where appropriate, I'd like to now do the same thing with places categorized as Offices.  WMEPH was extremely helpful with the first job, giving me the ability to fix most places with a single click, it would be nice to be able to do the same with Offices as well.

Note that I think this button should have no effect on the color-state of a place, similarly to "Force title case"

**Comment by mapomatic** [comment]
Added in v1.2.30
