### ISSUE TITLE
Errors since version 1.2.17

### ISSUE THREAD

**Issue by M1kep** [WazeUSA/WME-Place-Harmonizer#157]
So ever since I've upgrade to the 1.2.17 version of WMEPH I've found that the places no longer highlight. Also when I click "Run WMEPH" the console outputs the following:

![image](https://cloud.githubusercontent.com/assets/2661819/24581728/cdc13f20-16d5-11e7-956d-d0eff5af1545.png)

In the meantime I've reverted back to: https://github.com/WazeUSA/WME-Place-Harmonizer/blob/850ffb254f0fdc46681215a7a93b54855651c09d/WME-Place-Harmonizer.user.js

From the following commit:

https://github.com/WazeUSA/WME-Place-Harmonizer/commit/850ffb254f0fdc46681215a7a93b54855651c09d

I've encountered this on two machines, both running in Google Chrome.

**Comment by M1kep** [comment]
Also note, I experience this issue on 1.2.19

**Comment by mapomatic** [comment]
@M1kep helped me do some debugging of this issue.  Apparently some people start out in a scenario where the language reported in the WMEPH settings tab doesn't match what the code is using to determine the language (W.location.locale).  Once they switch to a different language in the setting tab, W.location.locale seems to stay sync'd and the issue goes away.  It may be that I'm using the wrong property in code, or there's a WME bug.  For now, the workaround is to tell people to switch language, and switch back.

**Comment by mapomatic** [comment]
Fixed
