### ISSUE TITLE
Lock PLA's to 3

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#160]
Feature request: According to the Wiki, parking lot areas should be locked at 3, but it seems that WMEPH is locking those at the regular state minimum lock level. Any chance that it can be adjusted so that PLAs get set to 3 when they meet the conditions where WMEPH would add the lock automatically?

http://www.waze.com/forum/viewtopic.php?f=819&t=215657&e=1617002

**Comment by mapomatic** [comment]
Tony is checking on whether or not the wiki guidance should still be in effect for PLA's.

**Comment by t0cableguy** [comment]
its a sheet setting to do this. So if the wiki guidance is correct then yes. I think the state minimum should suffice.

**Comment by mapomatic** [comment]
I've asked Tony if he was able to ask around and get feedback if state minimum should be OK.  Maybe we could/should poll the moderator group?

**Comment by mapomatic** [comment]
This was handled on the WMEPH Categories tab of the PNH sheet.  No code change necessary.  All PLA's set to 3, to match wiki guidance.
