### ISSUE TITLE
Limit Google link search distance

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#17]
Feature request.  Does this make sense in WMEPH?
Add something in wmeph like jnf had that limited the distance when searching for linked places

**Comment by tonestertm** [comment]
JNF author intends to bring the feature back as soon as it is technically possible by the means he was using, FWIW.  Unless you have another way.... ;)

**Comment by t0cableguy** [comment]
I like the idea, however it should be a toggle, which is set ON initially.

**Comment by mapomatic** [comment]
From bgodette:
> This code will modify outgoing ajax requests to the autocomplete search used by WME. jQuery conveniently provides a way to do this and is much cleaner that how I was doing it in JNF. Adding this to your init that runs after WME fully loads is all that's needed. It won't modify the passed options if it already contains a location, so if multiple scripts have this the cost is some extra latency.
```
$.ajaxPrefilter(function(options, originalOptions, jqXHR) {
   if (originalOptions.type === "GET" &&
      originalOptions.url === "/maps/api/place/autocomplete/json" &&
      !originalOptions.data.hasOwnProperty("location")) 
   {
      try {
         options.data = $.param($.extend(originalOptions.data, {
            location: W.map.getCenter().transform(W.map.getProjection(), W.map.displayProjection).lat + "," + W.map.getCenter().transform(W.map.getProjection(), W.map.displayProjection).lon,
            radius: 3200
         }));
      } catch(e) {
         console.log("modifying WME linked place search failed", e);
         console.log(options);
         console.log(originalOptions);
         console.log(jqXHR);
      }
   }
});
```

**Comment by mapomatic** [comment]
Implemented
