### ISSUE TITLE
Fuzzy Check for Bill Miller BBQ

### ISSUE THREAD

**Issue by jm6087** [WazeUSA/WME-Place-Harmonizer#174]
Can you add a fuzzy check for Bill Miller Bar-B-Q?

I have added primary as Bill Miller Bar-B-Q and alt name as Bill Miller BBQ but it appears a lot of people are entering Bill Miller's BBQ (or a variant of it)  There should not be the " 's "in the name

Also if it could match on just "Bill Miller" or "Bill Miller's"

**Comment by mapomatic** [comment]
I updated the PNH sheet to include that variation as well as "Bill Miller Barbecue" and "Bill Miller's Barbecue".
