### ISSUE TITLE
US Post Office (USPS) Hard-coded Information for SER

### ISSUE THREAD

**Issue by itzwolf** [WazeUSA/WME-Place-Harmonizer#175]
Approving US Post Office in the PNH Master List for SER causes some oddities with the banner being blank and there are some hard-coded items in the code for the primary name to be suggested as "USPS - Tampa", the URL, and the alt name which overwrite the PNH Spreadsheet data. SER would like to have this changed so the script functions like the rest of the regions but use the localized name that post offices have listed on the website. I've pasted some of the code below and the lines they start to help isolate the issue.

Line #1581:

                formatUSPS: {  // ### needs WL or not?
                    active: false, severity: 1, message: 'Localize the post office according to this region\'s standards for USPS locations (e.g., "USPS - Tampa")'
                },

This does not match PNH Sheet standard for US Post Office, in SER we would like to use the "US Post Office - Tampa" for example.

Line #1938

                        if (region === 'SER') {
                            W.model.actionManager.add(new UpdateObject(item, { aliases: ["United States Postal Service"] }));
                            fieldUpdateObject.aliases='#dfd';
                            highlightChangedFields(fieldUpdateObject,hpMode);
                        }

Line #3590:

                            if (hpMode.harmFlag && region === 'SER' && item.attributes.aliases.indexOf("United States Postal Service") === -1) {
                                actions.push(new UpdateObject(item, { aliases: ["United States Postal Service"], url: 'www.usps.com' }));
                                fieldUpdateObject.aliases='#dfd';

The above code can be removed so we utilize national standard data.

**Comment by mapomatic** [comment]
Fixed in v1.2.41
