### ISSUE TITLE
Disable Run button on places with PUR's

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#183]
Changes to places with at least one PUR cause save errors.

**Comment by StormeHawke** [comment]
I would say disable run button on places with non-approved PURs.  If the PUR is approved before running WMEPH then there's no error on save

**Comment by mapomatic** [comment]
Hmmm... Yeah now that I tinker with it more, do errors only occur if changes are made to "new place" PUR's?  I tried manually editing a place that had a details PUR waiting, then approved the PUR.  It updated the details that I changed with the PUR details, and saved fine.

**Comment by StormeHawke** [comment]
Take it a step further and if you approve the new place PUR, run WMEPH, then save, you'll be able to save successfully then as well.  It's an order of operations thing for new place PURs.  I don't think it matters either way for place update PURs

**Comment by mapomatic** [comment]
That does work, but the strange thing is that the edit panel is still grayed out after approving.  I assume it's probably a bug with WME (?).  Until that's fixed, I believe we should avoid having WMEPH edit anything the user can't edit manually, i.e. wait until after saving to show the Run button.

**Comment by jangliss** [comment]
@mapomatic this was what we were discussing in GHO on Saturday(?).  You can still make changes but some fields are marked as unedible by WME.  I think the final decision we came to was that if WME shows it disabled then we should not attempt to change it either.  The adjustments I just put in my fork handle the discussed state, but still allow the WMEPH button to show up for places that have already been approved/saved (ie flagged, new pics, etc).

**Comment by mapomatic** [comment]
Great, thanks!  Will check it out ASAP.

**Comment by mapomatic** [comment]
Just to follow up the most recent discussion, the plan is:
1) If new place PUR, disable Run button and auto-run.
2) If outside EA, disable auto-run but leave Run button.

I haven't researched/tested, but I think you might be able to use the arePropertiesEditable property, then check for a new place PUR.  If there's no new place PUR, assume it's outside of EA.
