### ISSUE TITLE
Flag un-GLinked place pins

### ISSUE THREAD

**Issue by StormeHawke** [WazeUSA/WME-Place-Harmonizer#19]
I haven't done a study but off the top of my head I would estimate that about 15% of the URs I fix could have been prevented were the pin for the place GLinked to its google equivalent.

As such I wanted to suggest that we have some way of flagging that a place isn't fully complete if it isn't GLinked.  I would say this behavior would only be enabled for editors of a rank to be able to GLink a place.  I was thinking leave it blue, Josh suggested adding another color option.  The specifics can be worked out, I just wanted to request some means of flagging these places (Needs to be white-listable)

**Comment by ehepner1977** [comment]
The blue highlight had meant that a place was complete enough to lock, but still missing some information.  So, if we used another color, what to do about places that should be blue as well?  Not opposed to adding GLink to the list of missing information, though.

**Comment by mapomatic** [comment]
I bounced the idea off a Local Champ and he thought as long as it only applied to ranks that could actually do external linking (3+, 4+?  I need to research that), blue would be fine.  He thought orange wasn't necessary, but if it was added as an optional setting, some people would find it useful.

I'm thinking orange would override blue, i.e. missing GLink is higher priority than other "non-required" info.

**Comment by tonestertm** [comment]
This is covered by the enhancement requested in Issue #2. (At least, it's a part of what I intended.) 
My humble opinion is that, except for certain types of places a pin should go neither blue nor green until it has a GLink, because these are such powerful things to have for proper capture and routing of search results.

**Comment by t0cableguy** [comment]
I'm not sure red is the right severity for this. that historically indicates a place with no address or name. Blue has historically indicated things are missing, but they are not critical. I'd hate for every place on the map to turn red overnight because it doesn't have a linked place to gmm.

**Comment by mapomatic** [comment]
From Xb:  
> Some of the less critical data was moved to the More Info tab. External Providers is right up front. Other than Description field, I consider anything on the General Tab to be critical data.

I don't disagree that it might be alarming to suddenly see red everywhere.  But if Champs are saying we should be filling it in, I'm not paid enough to disagree.  We could always try it in beta and if people take up pitchforks, re-evaluate.  What's beta for if we can't test things out in it?  :)

**Comment by Jakflash** [comment]
I agree External Providers link is usually important.  But not a fan of making it RED as all too frequently, there is not a link available in my experience.  However, I can support making it red in Beta to see what the reactions are.

**Comment by mapomatic** [comment]
Thanks for the feedback.  I'm curious to see if making it whitelistable would help in that regards.  I personally think adding another color might work as a compromise:

1. RED = missing critical info, won't lock
ORANGE = missing external provider (or other "more important" info if needed later), will lock (lower level editors can't do links anyway)
BLUE = missing other stuff, will lock
GREEN = good to go, will lock

That would allow you to see that a place is missing an external provider link.  You can check it and add it

**Comment by mapomatic** [comment]
Having said that, I will go ahead with making it red and we'll see what the reaction is.  Maybe afterword, take a vote (just have champs vote)?  This will be a big change and I don't think we're going to get 100% buy-in whatever we do.  Absent a dictator, I think a vote is the next best thing.  A champ vote would give it more weight.

**Comment by mapomatic** [comment]
#2

**Comment by t0cableguy** [comment]
I could settle on orange, however once again, there are often points that you cant find a GM link for. Another toggle under the highlights might be best.

**Comment by t0cableguy** [comment]
Mapomatic pushed an update that sets this red or blue depending on an option in the WMEPH Harmonize tab. A whitelist feature is also included to allow you to mark a place 100% (green) on the map. 
Red will not allow the place to lock, however blue will allow autolocking by the script.

"Treat "Missing External Provider" as non-critical (blue)"

In a future release he will add options for the following. 

"Disable External Providers check for Parking Lot Areas 
"Disable External Providers check for Parking Lot Areas without Operators"

Are there any other options that are reasonable?
