### ISSUE TITLE
Add option to filter places with locks higher than your rank

### ISSUE THREAD

**Issue by RavenDT** [WazeUSA/WME-Place-Harmonizer#21]
Under WMEPH tab, Highlighter settings:

Add option: [ ] Disable highlighting for lock > user

**Comment by t0cableguy** [comment]
URO+ provides this functionality at this time. Its a good idea (and I'm in no way shooting it down), however I think resources are better spent in places that functionality doesn't exist.

**Comment by RavenDT** [comment]
https://www.tribles.com/locations/Sterling -> http://https//www.tribles.com/locations/Sterling

Screenshot [here](http://i.imgur.com/nf80hzD.jpg).

**Comment by mapomatic** [comment]
Was this meant to be a reply to #22 ?

**Comment by t0cableguy** [comment]
Thanks for the fix.
