### ISSUE TITLE
URLs with https:// won't open when using 'Place Website' button

### ISSUE THREAD

**Issue by RavenDT** [WazeUSA/WME-Place-Harmonizer#22]
This is due to the fact that WMEPH strips http:// in the beginning of the address and then adds it back on later when creating the button.  Technically, a normalized URL (in IT perspective) is made up of a protocol, domain, then resource in the format: protocol://domainname/resource?key1=value1&key2=value2 (etc.)

Line 776:
`var m = s.match(/^http:\/\/(.*)$/i);  // remove http://`

Won't match "https://".  It could be easily fixed to match either, but then the protocol would still get stripped, and some websites don't perform a URL rewrite on http requests to change them to https.

There are three options to solve this problem:

1. Change the regex in line 776 to be `/^https?:\/\/(.*)$/i);` and hope that when the URL gets http:// added back again, the website forces a URL rewrite on their end.
2. Leave line 776 as-is, but instead change line 1659 from:
```
openPlaceWebsiteURL = 'http:\/\/' + newURL;
```
to
```
if ( /^http:/.test(newURL) ) {
   openPlaceWebsiteURL = 'http:\/\/' + newURL;
}
```
3. Change normalization procedures to include protocol (to include PNH table).  Change code to check to see if URL begins with http or https.  If it doesn't, prepend with "http://".

**Comment by t0cableguy** [comment]
I cant reproduce this issue. Can you provide some example permalinks? However I have had a long standing opinion that we use the simplest domain possible in the PNH list as well as the editor. thus bankofamerica.com, unitedrentals.com, bk.com have been the preferred format for many of the urls in the PNH list. You'll notice united rentals and bank of america are secured websites and pnh opens them correctly even with http:// at the front of the URL.

**Comment by RavenDT** [comment]
https://www.tribles.com/locations/Sterling -> http://https//www.tribles.com/locations/Sterling

Screenshot [here](http://i.imgur.com/nf80hzD.jpg).

**Comment by t0cableguy** [comment]
Even on your suggested website I still am not able to reproduce this. Is there a PNH entry for this location?

**Comment by t0cableguy** [comment]
line 1683
removing 'http:\/\/' + 
should solve this issue.

**Comment by RavenDT** [comment]
Sorry.  I was referencing line numbers in the master, not the beta branch.

**Comment by t0cableguy** [comment]
@RavenDT please check this and see if it functions properly for you.

**Comment by RavenDT** [comment]
@t0cableguy I checked it out on both computers using Chrome, and the fix doesn't work.

Somehow, the colon after the https is getting stripped as well.  It's not obvious where, though, so it may take some time.
