### ISSUE TITLE
Pnh updates only fixes one field

### ISSUE THREAD

**Issue by t0cableguy** [WazeUSA/WME-Place-Harmonizer#3]
Per press of the run button pnh only updates one or two fields from the PNH sheet

**Comment by t0cableguy** [comment]
I think you have this fixed in the branch. roll it out in beta. then we should push all these "minor" bugfixes, and post it to the forums in a new thread.

**Comment by mapomatic** [comment]
It's in beta.  Maybe tomorrow we can get production updated.  Closing this issue.
