### ISSUE TITLE
Bug: Adding House Number with no Street and no City

### ISSUE THREAD

**Issue by RavenDT** [WazeUSA/WME-Place-Harmonizer#32]
Adding House Number with no street and no city results in an unsaved change, but doesn't add the house number.

**Comment by RavenDT** [comment]
Note: Need to check if it is possible to even add a HN manually with "No Street" checked (I don't think it is).  If it's not, then the course of action would be to either infer the street name or fail to "Unable to add HN" appearing in the textbox.  And of course, double-check that the unsaved change counter doesn't increment.

**Comment by StormeHawke** [comment]
If No Street is checked (or no city) we need a way to populate those fields

**Comment by t0cableguy** [comment]
currently you can have a HN without city or street name. its not anything based in reality, but it can be done. an example of a problem child place.. lol https://www.waze.com/editor/?env=usa&lon=-81.15627&lat=27.59228&zoom=7&mode=0&venues=182714644.1827408583.253472&b=0

**Comment by mapomatic** [comment]
This appears to have been fixed.
