### ISSUE TITLE
Idea: Add Input box for missing URL (like phone)

### ISSUE THREAD

**Issue by RavenDT** [WazeUSA/WME-Place-Harmonizer#35]
Idea: Add Input box for missing URL (like phone).

**Comment by StormeHawke** [comment]
I second this.  And take it a step further - I'd like to see full inputs for all text field s so we don't have to switch back and forth between tabs constantly, including the address (Parsing from a pasted address would be even better)

**Comment by StormeHawke** [comment]
maybe the binding on the street name could be copied to a text field for the script so the street name auto-populates from nearby possibilities?

**Comment by t0cableguy** [comment]
Mark (well a couple people) had an idea at one time to make a single text input box that could guess what is in it.And we could have a couple buttons to force it to send the info to one spot or the other.

**Comment by RavenDT** [comment]
It could be possible, but I don't know if that'd be the best idea.  WMEPH has a bullet list of everything it finds wrong (or actions it takes like locking), and if we combine fields, it might get convoluted and/or confusing.

**Comment by t0cableguy** [comment]
this is a fake mockup of the idea. Not sure Its feasible. I know it would require a major change in the way wmeph pulls the information.
<img src=http://i.imgur.com/X5RiUfJ.png>

**Comment by mapomatic** [comment]
Completed
