### ISSUE TITLE
Idea: Make buttons and input fields slightly smaller

### ISSUE THREAD

**Issue by RavenDT** [WazeUSA/WME-Place-Harmonizer#37]
... And I do mean slightly.  I am willing to bet a lot of WMEPH users are older and their eyesight might not be so good.

One major win would be altering the bullet list so there wouldn't be so much wasted space between the bullets and the text.  That and it looks a bit tacky.

**Comment by t0cableguy** [comment]
http://i.imgur.com/X5RiUfJ.png An idea.

**Comment by t0cableguy** [comment]
another addition to this is possibly making the WL and Add buttons stack in a column to the right side of the panel.

**Comment by RavenDT** [comment]
This has been done in Beta and further improvements have been made in the Refactor by @mapomatic.

Closing issue.
