### ISSUE TITLE
Opening times should be able to infer AM / PM in some cases

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#38]
Entering "M-F: 10-7" yields "Mon-Fri 10:00-07:00".  Should be "Mon-Fri 10:00-19:00"

**Comment by t0cableguy** [comment]
so are we going to try to guess 1 or 2 is pm? There are some places that close at 1p on saturday, however many fast food restaurants and bars close at 1 or 2 am.
adding 10:00a-7:00p was always the way I have fixed this. Maybe wmeph could ask before assuming?

**Comment by StormeHawke** [comment]
I'd argue for sticking with the current behavior, except maybe throw the interpreted hours up next to the input box for verification.  Attempting to interpret whether a user meant AM or PM is going to generate a lot more pain than it fixes IMO.  I personally add the a/p to the hour numbers or convert to 24 hour time

**Comment by RavenDT** [comment]
>  There are some places that close at 1p on saturday, however many fast food restaurants and bars close at 1 or 2 am.

That's it! Do a category check.  If the place is a bar, restaurant or fast food, allow for assuming that the end time might be in the AM,

**Comment by mapomatic** [comment]
LOL - I was verifying last night that setting hours like "Fri 10:00am - 02:00am" actually works in the client.  Wasn't sure if adding hours into the next day was legitimate.  Then I started wondering, why do most places that stay open past midnight serve alcohol?  Booze + tired = bad things.

Anyway... You all brought up some good points I hadn't thought of.  I'll close this issue and add a new one to suggest adding some way to verify hours.
