### ISSUE TITLE
Spaces at the front of "brandparent#" hotels (Minor)

### ISSUE THREAD

**Issue by t0cableguy** [WazeUSA/WME-Place-Harmonizer#4]
Wmeph adds a space to the primary names of hotels. This is a low priority minor bug because WME automatically fixes this issue.

**Comment by RavenDT** [comment]
Question: Is there ever a time where we would keep text in front of the brandparent hotel name?

Example:
Raven's Hampton Inn - Tampa

Would we keep the "Raven's" part, or should the PNH always be "Hampton Inn - Tampa"?

**Comment by StormeHawke** [comment]
I'd be inclined to say "No", though possibly push the original text to an alt name in that situation, or factor it into the " - XXX" portion of the name, just on the off chance that some franchisee somewhere has a custom name that needs to be searchable

**Comment by t0cableguy** [comment]
I can't think of any off the top of my head. They would be rare. If one needed that functionality I think another PNH sheet flag might be necessary.

**Comment by mapomatic** [comment]
At or near line 2735, these lines may be removed:
```
//if (splix>-1) {
                            //    newName = newName.slice(0,splix) + ' ' + PNHMatchData[ph_name_ix] + ' ' + newName.slice(splix+PNHMatchData[ph_name_ix].length);
                            //    newName = newName.replace(/ {2,}/g,' ');
                            //}
```
However, this only works to turn the highlight green when running WMEPH manually.  When the initial "automatic" highlighting scan is done, it is blue even though nothing is missing.  Example:
https://www.waze.com/editor/?env=usa&lon=-84.55427&lat=38.01618&zoom=8&mode=0&venues=180486524.1805192922.1815124

**Comment by RavenDT** [comment]
That's the line that's causing the problem, but I was going to leave that code.  The only part I was going to remove was: `newName.slice(0,splix) + ' '`

Because that takes any text that appears in front of the brandparent name.  That's the reason I was asking if we needed to keep any of that text in any situation, because I was just gonna cut that.  Easy fix.
