### ISSUE TITLE
Secondary categories ignored in point/place recommendations

### ISSUE THREAD

**Issue by StormeHawke** [WazeUSA/WME-Place-Harmonizer#41]
Example:
https://www.waze.com/editor/?env=usa&lon=-85.98631&lat=40.12007&zoom=0&venues=179569041.1795952556.1225990

Waze seems to have its own ideas as to what the "primary" category of a place should be, regardless of the order we put the categories in.  WMEPH should look to see if any of the assigned categories for a place are area types before making a recommendation to convert to a point place.

**Comment by t0cableguy** [comment]
this is something we need to figure out what to do about. IDK why this changed in the editor, but it seems the dev's don't care enough to change it back.
