### ISSUE TITLE
Limit phone numbers to 10 digits.

### ISSUE THREAD

**Issue by StormeHawke** [WazeUSA/WME-Place-Harmonizer#42]
Occasionally I'll run across a place with a phone number spelled out in letters (E.G. White Castle's official phone number is 1-800-THE-CRAVE).  The phone number parser should be able to parse out what numbers those correspond to in a traditional phone keypad

**Comment by t0cableguy** [comment]
pretty sure it already does this. Have you tried?

**Comment by t0cableguy** [comment]
fixed issue with lowercase letters in phone numbers in v1.1.51.
Thanks mapomatic.

**Comment by StormeHawke** [comment]
Ahh I see.  This phone number has one extra character
1-800-THE-CRAVE

The E/3 would just be ignored by the phone system if you dialed it.  So maybe we need something that takes something that looks like a phone number and saves off the first ten digits (skipping the 1- part)?

**Comment by t0cableguy** [comment]
shouldn't be hard. We are already removing the 1 from the beginning. That is probably what is fouling the system up. The regex isn't considering the trailing letter.

**Comment by t0cableguy** [comment]
wmeph is flagging these as invalid phone numbers. Not sure what else we need to do with this, but it should definitely crop the last number/letter if its longer than 10 digits.

**Comment by StormeHawke** [comment]
That's the problem.  1-800-THE-CRAVE is a valid phone number and should be accepted, with the last "E" left off.  An optional 11th digit on the end of the regex should be accepted.  A lookahead regex like this might do it: `(?=[a-zA-Z]?)`

**Comment by mapomatic** [comment]
This should now be fixed in 1.1.80
