### ISSUE TITLE
Refactoring - split code logically intuitive separate related files 

### ISSUE THREAD

**Issue by StormeHawke** [WazeUSA/WME-Place-Harmonizer#49]
One big monolithic file makes it harder to track down issues. Splitting the code into separate files based on logical relationships (say the hours parser could have its file or group of files, the services buttons another). This makes maintenance and development of new features much easier. You would then run a minifier to combine everything into a single script for tampermonkey to consume

**Comment by RavenDT** [comment]
I was thinking the same thing; but, I personally, am not sure how that works with user scripts.

As an alternative, in the refactoring process, if we just simply reorganize the code into a better fashion, it would be way easier to maintain.

The way the code is written now:
```
// Globals

// GM/TM Header

// Main function
function () {
    // Declare variables
    // Array prototypes (for Firefox fix)

    // All function declarations, main code, all jumbled together and in no clear order.
```

The way we could/should write the code:
```
// Globals

// GM/TM Header

// Constants (like URLs to google sheets)

// Subroutine function declarations
// [ Pretty much all logic should be moved here in their own separate functions ]

// Main function
function() {
    // Only code for bootstraps and setting timeouts
}
```

**Comment by t0cableguy** [comment]
<img src=https://i.imgur.com/nQJbc3d.png>

just FYI if we minify the code we will not be able to use GF to host the script, not that I'm pining to use it.

**Comment by StormeHawke** [comment]
I was thinking more on the level of minimal minification that just concats all the separate files together into a single published version

**Comment by RavenDT** [comment]
@t0cableguy The minification they are referring to I believe means eliminating all whitespace in order to reduce script size.  This is an accepted practice for published libraries like jQuery.

Because WMEPH is downloaded once and run locally, there's no need to do that.

**Comment by RavenDT** [comment]
It looks like we'll be doing some of this.  I've found some code that really shouldn't be inside the main script.

We can host the files here on github as a part of the repo, and then just load them using `@require` or `@resource`.

**Comment by RavenDT** [comment]
We started doing this.  Going to mark this as done.
