### ISSUE TITLE
Rest area checks not functioning properly

### ISSUE THREAD

**Issue by t0cableguy** [WazeUSA/WME-Place-Harmonizer#5]
Rest area checks not functioning as intended.

**Comment by mapomatic** [comment]
@t0cableguy, can you list specific details of what's not functioning as intended?

**Comment by mapomatic** [comment]
For at least some existing rest areas (like this one: https://beta.waze.com/editor/?env=usa&lon=-84.62956&lat=38.93581&zoom=4&mode=0&venues=180486533.1804668726.382515)
Clicking the Yes button next to "Is this a rest area" appears to make 8 changes (according to # on save button) and then highlight changes from red to green.  But changes can not be undone.

I tried creating a rest area from scratch and saving it.  Clicking Yes next to "Is this a Rest Area" only created 4 changes, and those _could_ be undone.  After saving the 4 changes and refreshing, the rest area showed up red again, with the "Is this a Rest Area" button still visible.

**Comment by t0cableguy** [comment]
Since this affects editing any rest area I'd consider this a major bug, and of a reasonably high priority. However most rest areas are locked to 5 and updates to those locations are limited to users of sufficient rank, Thus this isn't the biggest fish to fry on the major bug list.

**Comment by mapomatic** [comment]
Tentative fix in v1.1.61
