### ISSUE TITLE
Refactor: "use strict" ?

### ISSUE THREAD

**Issue by RavenDT** [WazeUSA/WME-Place-Harmonizer#50]
I noticed WMEPH doesn't "use strict".

I want to know what you guys think about maybe as a part of the refactoring process, attempting to "use strict" coding practices in an effort to reduce "loose" code.

Advantages:
- Makes it easier to write "secure" JavaScript
- Changes previously accepted "bad syntax" into real errors.
- Enforce variable scoping.  Normally, you attempt to assign a value to a variable out of scope, it creates a new global variable.  In strict mode, it'll throw an error.
- Will receive error feedback assigning values to non-writable properties
- Any assignment to non-writable property, getter-only property, non-existing property, non-existing variable, non-existing object, will throw an error.

Disadvantages:
- It'll probably take a lot of work to implement.

What are your thoughts?

**Comment by t0cableguy** [comment]
Any refactoring is up to you and MapOMatic. if you want to rebuild the code from the ground up, be my guest. as long as it can be deciphered I think any improvement on workability and bug reporting is worth it.

**Comment by mapomatic** [comment]
I'm all for anything that helps prevent silent bugs.

**Comment by RavenDT** [comment]
So, turns out a bunch of functions near the end of the code had "use strict" declared in them.  I took those out because I put the "use strict" at the very beginning of the script.  It's helped a lot with ambiguity and debugging thus far in the Refactor.

I am going to mark this as done.
