### ISSUE TITLE
Using WL on an unsaved place doesn't work properly.

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#51]
Places are initially assigned a temporary negative ID value starting at -100 (and decrementing with each new place) until they are saved and they receive their permanent ID.  The temporary ID is stored in the whitelist if applied before the place is saved.  Once saved, the place "loses" its WL.  Also, the next time the page is refreshed, the starting ID value for new places resets to -100, so any whitelisted issues previously assigned to those negative ID's will be applied to new places (though they will also "lose" them once saved).

A couple potential options:
1. Listen for a place save, retrieve the new ID, and assign it to WL entries with the old temporary ID
2. Prevent WL until the place is saved (i.e. until it has a positive ID #).

From a usability perspective, item 1 would be the best option if it is possible.

**Comment by t0cableguy** [comment]
i'd imagine option 2 will be easiest to deploy. It also reinforces the safe often save frequently mentality. but yes option 1 would be best.

**Comment by mapomatic** [comment]
I believe the way to implement #1 is to use the objectssynced event of the venues collection.  It will return an array of objects with the old (temporary) ID and the new ID, so WL info can be copied from old to new.

`W.model.venues.on('objectssynced', function(e){e.forEach(function(item){console.log(item._prevID);});})`

**Comment by mapomatic** [comment]
fixed in v1.1.62
