### ISSUE TITLE
Areas and Points being flagged as stacked.

### ISSUE THREAD

**Issue by t0cableguy** [WazeUSA/WME-Place-Harmonizer#58]
examples
[Area for Chevron](https://www.waze.com/editor/?env=usa&lon=-118.09987&lat=33.91738&zoom=6&mode=0&venues=158531923.1585319232.3259)

[Point for Extramile](https://www.waze.com/editor/?env=usa&lon=-118.09987&lat=33.91738&zoom=6&mode=0&venues=158531923.1585319232.3122909)

**Comment by mapomatic** [comment]
fixed in 1.1.59
