### ISSUE TITLE
Keep hours banner line visible always

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#64]

**Comment by helifino** [comment]
Seconded (actually, I made the same request to bmtg a while back)

**Comment by helifino** [comment]
Consider hiding line if 24/7 attribute is checked.

**Comment by StormeHawke** [comment]
Thirded, though I agree 24/7 should go ahead and hide it

**Comment by mapomatic** [comment]
Added, but not hiding for 24/7 yet.  Added as issue #85
