### ISSUE TITLE
Add option to not check PLA's for missing external provider

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#70]
Also, maybe add an option to only check operator-run lots.

**Comment by t0cableguy** [comment]
also possibly add an option to ignore on the map highlights options. like for hours.

**Comment by mapomatic** [comment]
@t0cableguy, do you mean ignore for highlights / locks, but leave the "missing" message in the banner?

**Comment by t0cableguy** [comment]
Yes. In the map have the same option like hours does(ie show green on map), but for external providers.
