### ISSUE TITLE
brandParent# not functioning in beta wme

### ISSUE THREAD

**Issue by t0cableguy** [WazeUSA/WME-Place-Harmonizer#71]
multiple match issues because brandparent isn't working in wme beta.

**Comment by mapomatic** [comment]
Do you have an example we can use to see the problem and test?

**Comment by t0cableguy** [comment]
Mostly any Marriott, Hilton, or major hotels staybridge does.

**Comment by mapomatic** [comment]
I'm not sure if this was ever fixed, but I don't have enough info to go forward with debugging so I'm closing this out for now.
