### ISSUE TITLE
Add Street doesn't work if there's no city.

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#72]
Need to add a "No city" entry box.

**Comment by tonestertm** [comment]
Had an interesting experience perhaps related to this: The place had no HN, Street, nor City. I tried adding the HN first, the box cleared from the banner, but the HN didn't show in the address box. I saved, and it was in the data. Went back, added the City directly to the WME address dialog, which then demanded that I add the Street. Saved, but no HN showed up. Checking the data again, the houseNumber was now gone.

**Comment by mapomatic** [comment]
I've disabled the "No street" line until a city is added.  Adding a "No city" entry box will take a bit more work.

**Comment by mapomatic** [comment]
Disabled the "Add street" input until a city is set.
