### ISSUE TITLE
Add a line to show current HN/street.

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#75]
A lot of places have the wrong street and/or HN, but it's not obvious unless you scroll to the bottom to see the address.  Add a line that always displays HN/street.

**Comment by t0cableguy** [comment]
Would it be possible to move the address "tool" to the top using css?

**Comment by helifino** [comment]
It should be, it's enclosed in its own labeled div...

**Comment by mapomatic** [comment]
@justins83 will add a feature to PIE that will move the address to the top.
