### ISSUE TITLE
ExtraMile stripped from Place Name

### ISSUE THREAD

**Issue by turbomkt** [WazeUSA/WME-Place-Harmonizer#77]
When editing Chevron with ExtraMile...it says to append it if there is one.  Then, adding ExtraMile, it strips the ExtraMile off.

**Comment by t0cableguy** [comment]
Isn't this better handled by making them another point place? Most I've seen the extra mile is a point place.

**Comment by turbomkt** [comment]
Probably.  But if that's the way we go then we need to remove the part where it says to append ExtraMile. Right?

**Comment by helifino** [comment]
Since the ad team went around and placed points for every EM location a few months back, script should check if there's a EM place point nearby.

**Comment by t0cableguy** [comment]
If you name a place ExtraMile it will do duplicate checking, Not sure if we need to code in a separate check for this.

**Comment by t0cableguy** [comment]
What do we want to change "extramile" flag to? 
I'm leaning more towards having a separate convinience store and having the gas station separate due to the problem of the primary not showing up in search. Its another heated debate in some regoins.

**Comment by RavenDT** [comment]
Isn't ExtraMile a convenience store that sells gas?

In my mind, I would think it should be one area place for [Gas Station,
Convenience Store] with ExtraMile in the name and Chevron in the alternate
name (unless the app search picks up the gas brand name).

**Comment by helifino** [comment]
Because of the way it's advertised in other media (tv, print) without a 
gas station, plus the fact that it's owned by multiple gas brands, plus 
when it was last advertised in Waze was as a separate place, I'd agree 
on separate places.

**Comment by t0cableguy** [comment]
when you search for gas in the app it only shows the brand, not the primary name. The primary name shows on the map in the app, but most people are going to use search, or they will just go to the gas station of their choice.

**Comment by t0cableguy** [comment]
Ok, they've changed this some in the app. In search it shows the full name, but when you tap the item, it shows the gas brand, if its a "gas station". thus my reasoning for them to have separate place points.

**Comment by RavenDT** [comment]
So, what was the consensus on this?

**Comment by t0cableguy** [comment]
Closing as it was addressed in chat. Extramile is a convenience store so it will get a separate point
