### ISSUE TITLE
readme.md Beta link is 404

### ISSUE THREAD

**Issue by helifino** [WazeUSA/WME-Place-Harmonizer#79]

**Comment by t0cableguy** [comment]
Where is the link you used for the readme? Did it come from here?

**Comment by helifino** [comment]
https://github.com/WazeUSA/WME-Place-Harmonizer/blob/master/readme.md

**Comment by t0cableguy** [comment]
Are you typing it in? Beta has a capital b and it's required to be capitalized otherwise it will be a 404.

**Comment by helifino** [comment]
Clicking on the link

**Comment by RavenDT** [comment]
Fixed.  Thanks, helifino!

**Comment by t0cableguy** [comment]
Thanks.
