### ISSUE TITLE
Detect (staff) in Created by when a place has no Updates

### ISSUE THREAD

**Issue by tonestertm** [WazeUSA/WME-Place-Harmonizer#83]
Waze3rdParty is creating garbage places on the map, but there are usually no Updates (yet), so WMEPH doesn't detect them as having been last handled by (staff). 
When a place has no Update information, the script should look at the Creation information to see if staff was involved.

**Comment by t0cableguy** [comment]
need to add a check for if updatedby=null then createdby="bot"
