### ISSUE TITLE
"Comcast" being converted to "CoMcAst"

### ISSUE THREAD

**Issue by StormeHawke** [WazeUSA/WME-Place-Harmonizer#91]
"Comcast" is correct.  No PNH match.  Tested surrounding places to see if similar behavior happens, and the behavior was normal

![image](https://cloud.githubusercontent.com/assets/540587/22021976/f109342e-dc8d-11e6-8db4-5f5cba3e2304.png)

Example place:
https://www.waze.com/editor/?env=usa&lon=-86.07798&lat=39.87764&zoom=6&mode=0&venues=179503503.1795166100.2427448

**Comment by mapomatic** [comment]
Lol, I think that's part of the code to correctly capitalize McWhatever.  Should be an easy fix.
